### ISSUE TITLE
Busy port catching

### ISSUE THREAD

**Issue by QuRa** [isaacloud/local-api#4]
At the time when the port is busy, throw is erroneously handled:

>$ localapi run ./application.raml -p 3334
info: LocalAPI 1.3.6 by IsaaCloud.com
info: [localapi] Run app
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: listen EADDRINUSE
    at exports._errnoException (util.js:746:11)
    at Server._listen2 (net.js:1156:14)
    at listen (net.js:1182:10)
    at Server.listen (net.js:1267:5)
    at EventEmitter.listen (/usr/lib/node_modules/localapi/node_modules/express/lib/application.js:617:24)
    at /usr/lib/node_modules/localapi/lib/localApi.js:61:18
    at _fulfilled (/usr/lib/node_modules/localapi/node_modules/q/q.js:834:54)
    at self.promiseDispatch.done (/usr/lib/node_modules/localapi/node_modules/q/q.js:863:30)
    at Promise.promise.promiseDispatch (/usr/lib/node_modules/localapi/node_modules/q/q.js:796:13)
>    at /usr/lib/node_modules/localapi/node_modules/q/q.js:604:44

**Comment by asikorski** [comment]
@QuRa Better command line support will be added in 1.5.0

**Comment by wszydlak** [comment]
Implemented in newest LocalApi version (v1.4.5)
